name: Run Blum Airdrop Every60 Minutes

on:
  schedule:
    - cron: '*/60 * * * *'  # 60 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send a request using curl
        run: |
          curl https://idx.relaxcoding.com
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Create .env file
        run: |
          echo "QUERY_ID=${{ secrets.QUERY_ID }}" >> .env

      - name: Run Blum Airdrop
        run: go run blum.go
        
      - name: Send a request using curl
        run: |
          curl https://idx.relaxcoding.com
